"""esquema base (fase 1)

Revision ID: 0001
Revises:
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_units",
        sa.Column("course_key", sa.String(length=130), nullable=False),
        sa.Column("unit_key", sa.String(length=130), nullable=False),
        sa.Column("curricular_year", sa.Integer(), nullable=True),
        sa.Column("semester", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("course_key", "unit_key"),
    )
    op.create_table(
        "courses",
        sa.Column("key", sa.String(length=130), nullable=False),
        sa.Column("institution", sa.String(length=64), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("degree", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("ext", sa.String(length=16), nullable=False),
        sa.Column("mime", sa.String(length=128), nullable=False),
        sa.Column("original_path", sa.String(length=64), nullable=False),
        sa.Column("parent", sa.String(length=36), nullable=True),
        sa.Column("visibility", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("source_path", sa.Text(), nullable=True),
        sa.Column("batch", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.String(length=32), nullable=True),
        sa.Column("unit", sa.String(length=130), nullable=True),
        sa.Column("course", sa.String(length=130), nullable=True),
        sa.Column("document_type", sa.String(length=64), nullable=True),
        sa.Column("academic_year", sa.String(length=9), nullable=True),
        sa.Column("assessment_type", sa.String(length=64), nullable=True),
        sa.Column("exam_season", sa.String(length=64), nullable=True),
        sa.Column("assessment_number", sa.Integer(), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=True),
        sa.Column("solution_origin", sa.String(length=64), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column("review_reasons", sa.JSON(), nullable=False),
        sa.Column("classification", sa.JSON(), nullable=False),
        sa.Column("sources", sa.JSON(), nullable=False),
        sa.Column("history", sa.JSON(), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("pages", sa.Integer(), nullable=False),
        sa.Column("words", sa.Integer(), nullable=False),
        sa.Column("rendition", sa.String(length=80), nullable=True),
        sa.Column("pages_needing_transcription", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_documents_owner"), ["owner"], unique=False)
        batch_op.create_index(batch_op.f("ix_documents_sha256"), ["sha256"], unique=False)
        batch_op.create_index(batch_op.f("ix_documents_unit"), ["unit"], unique=False)

    op.create_table(
        "extractions",
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("extractor", sa.String(length=32), nullable=False),
        sa.Column("extractor_version", sa.Integer(), nullable=False),
        sa.Column("pages", sa.JSON(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("sha256"),
    )
    op.create_table(
        "institutions",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("acronym", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("slug"),
    )
    op.create_table(
        "meta",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "near_duplicates",
        sa.Column("doc_a", sa.String(length=36), nullable=False),
        sa.Column("doc_b", sa.String(length=36), nullable=False),
        sa.Column("distance", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("doc_a", "doc_b"),
    )
    op.create_table(
        "proposals",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "topics",
        sa.Column("unit_key", sa.String(length=130), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("parent_slug", sa.String(length=64), nullable=True),
        sa.Column("sort", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("unit_key", "slug"),
    )
    op.create_table(
        "unit_editions",
        sa.Column("unit_key", sa.String(length=130), nullable=False),
        sa.Column("academic_year", sa.String(length=9), nullable=False),
        sa.Column("lecturers", sa.JSON(), nullable=False),
        sa.Column("assessment_method", sa.Text(), nullable=True),
        sa.Column("assessments", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("unit_key", "academic_year"),
    )
    op.create_table(
        "units",
        sa.Column("key", sa.String(length=130), nullable=False),
        sa.Column("institution", sa.String(length=64), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("acronym", sa.String(length=32), nullable=True),
        sa.Column("ects", sa.Float(), nullable=True),
        sa.Column("lecturers", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "users",
        sa.Column("login", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("preferences", sa.JSON(), nullable=False),
        sa.Column("enrollments", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("login"),
    )
    op.create_table(
        "vocab_terms",
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("is_assessment", sa.Boolean(), nullable=False),
        sa.Column("is_submission", sa.Boolean(), nullable=False),
        sa.Column("is_syllabus", sa.Boolean(), nullable=False),
        sa.Column("is_fallback", sa.Boolean(), nullable=False),
        sa.Column("sort", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("kind", "slug"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vocab_terms")
    op.drop_table("users")
    op.drop_table("units")
    op.drop_table("unit_editions")
    op.drop_table("topics")
    op.drop_table("proposals")
    op.drop_table("near_duplicates")
    op.drop_table("meta")
    op.drop_table("institutions")
    op.drop_table("extractions")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_unit"))
        batch_op.drop_index(batch_op.f("ix_documents_sha256"))
        batch_op.drop_index(batch_op.f("ix_documents_owner"))

    op.drop_table("documents")
    op.drop_table("courses")
    op.drop_table("course_units")
    # ### end Alembic commands ###
